name: hypegienic
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  collection: ^1.16.0
  device_info: ^2.0.3
  cupertino_icons: ^1.0.5
  flutter_config: ^2.0.0
  flutter_flux: ^4.1.3
  flutter_svg: ^0.22.0
  url_launcher: ^6.1.6
  shared_preferences: ^2.0.15
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  firebase_crashlytics: ^3.0.5
  firebase_messaging: ^14.1.0
  firebase_dynamic_links: ^5.0.5
  mapbox_gl: ^0.16.0
  geolocator: ^9.0.2
  webview_flutter: ^3.0.4
  socket_io_client: ^2.0.0
  flare_flutter: ^3.0.2
  cached_network_image: ^3.2.1
  animated_text_kit: ^4.2.2
  app_tracking_transparency: ^2.0.3
  app_settings: ^4.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/asset/icon/hypegienic.png"

flutter:
  uses-material-design: true
  assets:
    - lib/asset/image/
    - lib/asset/animation/
  fonts:
    - family: Arimo
      fonts:
        - asset: lib/asset/font/arimo_regular.ttf
        - asset: lib/asset/font/arimo_medium.ttf
          weight: 500
        - asset: lib/asset/font/arimo_semibold.ttf
          weight: 600
        - asset: lib/asset/font/arimo_bold.ttf
          weight: 700
    - family: Exan
      fonts:
        - asset: lib/asset/font/exan.woff
